.ifndef __GRAPHICS_INC__
__GRAPHICS_INC__ = 1

.import gfx_menu1Tiles
.import gfx_menu1Map
.import gfx_menu1Pal

.import gfx_menu2Tiles
.import gfx_menu2Map
.import gfx_menu2Pal

.import gfx_plasma_mapTiles
.import gfx_plasma_mapPal
.import gfx_plasma_map_pal6Pal

.import gfx_charTiles
.import gfx_charPal

.import gfx_logoTiles
.import gfx_logoMap
.import gfx_logoPal

.import gfx_map_backgroundTiles
.import gfx_map_backgroundMap
.import gfx_map_backgroundPal

.endif
