.ifndef __SPACEPLANE_INC__
__SPACEPLANE_INC__ = 1
;-------------------------------------------------------------------------;
.global DoMode7Map, DoSpacePlane
.global PlasmaMapSpacePlaneDMA, SpacePlane, SpacePlaneDMA, TestQuit
;-------------------------------------------------------------------------;
.globalzp map_xpos, map_ypos, storage1, storage2, storage5, storage6
.globalzp storage7, storage8
;-------------------------------------------------------------------------;
.endif
