#ifndef HELP_H
#define HELP_H

const char USAGE[] = {
	"\nConvert impulse tracker modules to an SNES SPC700 sound file or soundbank.\n"
	"Usage: smconv [options] [input]\n\n"
};

const char OPTIONS[] = {
	"Mandatory arguments to long options are mandatory for short options too.\n"
	"  -d, --driver [driver]      [driver] may be one of the following:\n"
	"                             celes     - uses many IT commands for other\n"
	"                                         features. it has no sfx support.\n"
	"                             snesmod*  - the default sound driver.\n"
	"                             pitchmod  - pitch modulation and noise generation.\n"
	"                             supernofx - special features and no sfx support.\n"
	"                             help      - additional information.\n"
	"  -h, --hirom                Use HIROM mapping mode for soundbank.\n"
	"  -i, --info                 Provide driver information.\n"
	"  -o, --output [file]        Specify output file or file base. This is required\n"
	"                             for soundbank mode.\n"
	"  -s, --soundbank            Create a soundbank instead of creating an SPC.\n"
	"                             This mode allows for multiple songs.\n"
	"  -v, --verbose              Enable verbose output to view how much RAM the\n"
	"                             modules will use.\n"
	"      --help                 Show Help.\n"
	"      --doc                  Show composition documentation.\n\n"
	"EXAMPLES:\n"
	"  smconv -s -o build/soundbank -h song1.it song2.it     # Two song soundbank\n"
	"  smconv -s -o build/soundbank -h -d supernofx input.it # supernofx driver\n"
	"  smconv input.it                                       # IT->SPC\n"
};

const char DRIVER_INFO[] = {
	"DRIVER:        DESCRIPTION:\n"
	"  snesmod      SNESMod is the default driver when the [-d|--driver] option\n"
	"               isn't used. This is Mukunda's original driver with a couple of\n"
	"               bug fixes and support for vibrato waveform (S3x)\n\n"
	"  celes        This driver uses many IT commands for other features.\n\n"
	"  pitchmod     This driver has the same features as snesmod as well as support\n"
        "               for pitch modulation and noise generation which were added by\n"
	"               KungFuFurby. Special care must be taken if you use these\n"
	"               features and have sound effects.\n\n"
	"  supernofx    In addition to pitchmod features, Super SNESMod lets you\n"
	"               modify echo delay, echo feedback, and the echo coeffiecents. It\n"
	"               does not have support for sound effects.\n\n"
};
	
const char DOC[] = {
	".-----------------------------------------------------------------------.\n"
	"|                       SNESMOD COMPOSITION RULES                       |\n"
	"|-----------------------------------------------------------------------|\n"
	"|                                                                       |\n"
	"| Impulse tracker format must be used. 8 Channels MAX.                  |\n"
	"|                                                                       |\n"
	"| Notes can not exceed 128KHz playback rate.                            |\n"
	"|                                                                       |\n"
	"| The module must be in instrument mode and must have instruments.      |\n"
	"|                                                                       |\n"
	"| DO NOT USE UNDEFINED INSTRUMENTS, they will not silence the channel,  |\n"
	"| THEY WILL CAUSE MALFUNCTION!                                          |\n"
	"|                                                                       |\n"
	"| The 64 or less samples must fit within 58K of memory. This is AFTER   |\n"
	"| BRR compression. 8-bit samples will be reduced to 9/16 size. 16-bit   |\n"
	"| samples will be reduced to 9/32 size.                                /\n"
	"|                                                                     |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                USAGE                                |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| To use alternate versions of SNESMOD edit DRIVER in your Makefile.  |\n"
	"|                                                                     |\n"
	"| DRIVER		:= PITCHMOD                                   |\n"
	"| ASFLAGS		:= --cpu 65815 -S -D HIROM -D $(DRIVER)       |\n"
	"| SMCONVFL		:= --hirom --driver $(DRIVER) --soundbank \\   |\n"
	"|                          --output soundbank                         |\n"
	"|                                                                     |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                            CUT FEATURES                             |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| This is not a complete IT implementation, here are some IT features |\n"
	"| that you must not use:                                              |\n"
	"|                                                                     |\n"
	"| * New Note Actions are not supported.                               |\n"
	"| * Complex sample mapping is not supported.                          |\n"
	"|     Only the center entry in each instruments sample map will be    |\n"
	"|     used for the entire map! (and the note values are ignored!!!)   |\n"
	"| * Pitch envelope is not supported.                                  |\n"
	"| * No stereo samples!!                                               |\n"
	"| * Envelope sustain must remain on one node only.                    |\n"
	"| * Envelope nodes must be only 1 to 256 ticks apart.                 |\n"
	"| * Envelope carry is not supported.                                  |\n"
	"| * Random volume/panning variations are not supported.               |\n"
	"| * Pitch/Pan separation is not supported.                            |\n"
	"| * 'Old effects' must be set to 'off'.                               |\n"
	"| * Only linear frequency mode is supported.                          |\n"
	"| * Gxx must not share memory with Exx/Fxx.                           |\n"
	"| * Auto-vibrato is not supported.                                    |\n"
	"| * Filters are not supported.                                        |\n"
	"| * These volume effects are not supported:                           |\n"
	"|     Ex, Fx, Gx, Hx                                                  |\n"
	"| * These effects are partially/not supported:                        |\n"
	"|     Cxx - xx must be zero.      Break to row                        |\n"
	"|     Ixx - not supported         Tremor                              |\n"
	"|     S1x - not supported         Set glissando control               |\n"
	"|     S2x - not supported         Set finetune                        |\n"
	"|     S33 - not supported         Set vibrato waveform to random      |\n"
	"|     S43 - not supported         Set tremolo waveform to random      |\n"
	"|     S53 - not supported         Set panbrello waveform to random    |\n"
	"|     S7x - not supported         Not supported                       |\n"
	"|     S9x - not supported         (this is used for special features) |\n"
	"|     SAy - not supported         Set high value of sample offset     |\n"
	"|     SBx - not supported         Pattern loop, sorry :(              |\n"
	"|     Zxx - not supported         (this is used for special features) |\n"
	"|                                                                     |\n"
	"| And because mukunda is so damn lazy these are also not supported:   |\n"
	"|  panning envelopes                                                  |\n"
	"|                                                                     |\n"
	"| * '+++' patterns ARE supported!!!                                   |\n"
	"|                                                                     |\n"
	"|:::::::::::::::::::::::::::. ........... .:::::::::::::::::::::::::::|\n"
	"|  ENABLE ADSR AND SET AD  ::             ::  ENABLE ADSR AND SET AD  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| Mxx ::  SNESMod :: Pitchmod ::               ::                     |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"|    M7F - Use direct gain mode for the current channel [default]     |\n"
	"| M80-FF - Enable ADSR for current channel and set the attack and     |\n"
	"|          decay rate (%%Adddaaaa)                                     |\n"
	"|                                                                     |\n"
	"| * Volume commands will be ignored                                   |\n"
	"|                                                                     |\n"
        "| * M00-40 sets channel volume in all drivers per IT spec             |\n"
	"|                                                                     |\n"
	"|:::::::::. ...............................................  .::::::::|\n"
	"|  ECHO  ::                                                 ::  ECHO  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S0x ::  SNESMod :: Pitchmod ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S01 - Turn on echo for channel                                      |\n"
	"| S02 - Turn off echo for channel                                     |\n"
	"| S03 - Turn on echo for all channels                                 |\n"
	"| S04 - Turn off echo for all channels                                |\n"
	"|                                                                     |\n"
	"| * The other echo settings for the module can be configured during   |\n"
	"|   conversion. See 'SPECIAL SONG MESSAGE COMMANDS'                   |\n"
	"|                                                                     |\n"
	"| * When setting the Echo Delay parameter, you lose '2K x D' of       |\n"
	"|   sample memory from the SPC.                                       |\n"
	"|                                                                     |\n"
	"|:::::::::::::::::::::. ....................... .:::::::::::::::::::::|\n"
	"|  PITCH MODULATION  ::                         ::  NOISE GENERATION  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S0x ::          :: Pitchmod ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S05 - Turn on pitch modulation for one channel                      |\n"
	"| S06 - Turn off pitch modulation for one channel                     |\n"
	"| S07 - Turn on pitch modulation for all channels                     |\n"
	"| S08 - Turn off pitch modulation for all channels                    |\n"
	"| S09 - Turn on noise generation for one channel                      |\n"
	"| S0A - Turn off noise generation for one channel                     |\n"
	"| S0B - Turn on noise generation for all channels                     |\n"
	"| S0C - Turn off noise generation for all channels                    |\n"
	"|                                                                     |\n"
	"| * The global volume should always be maximum, or else your pitch    |\n"
	"|   modulation might be weak.                                         |\n"
	"|                                                                     |\n"
	"|::::::::::. ............................................. .::::::::::|\n"
	"|  RESET  ::                                               ::  RESET  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S0x ::          ::          ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S0D - Reset echo delay to default defined in the song message       |\n"
	"| S0E - Reset echo volume to default defined in the song message      |\n"
	"| S0F - Reset echo feedback to default defined in the song message    |\n"
	"|                                                                     |\n"
	"|::::::::::::::::::::. ......................... .::::::::::::::::::::|\n"
	"|  NOISE FREQUENCY  ::                           ::  NOISE FREQUENCY  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S1x-S2x ::      :: Pitchmod ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S1x-S2x - Noise frequency, -10h to get your frequency. This         |\n"
	"|           automatically disables noise frequency sweep if using     |\n"
	"|           Super SNESMod NoFX.                                       |\n"
	"|                                                                     |\n"
	"| * Applies to all channels that have noise enabled.                  |\n"
	"|                                                                     |\n"
	"|:::::::::::::::::::::. ....................... .:::::::::::::::::::::|\n"
	"|  VIBRATO WAVEFORM  ::                         ::  VIBRATO WAVEFORM  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S3x  :: SNESMod  :: Pitchmod ::               :: Super SNESMod NoFX |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S30 - Sine [default]                                                |\n"
	"| S31 - Ramp down                                                     |\n"
	"| S32 - Square                                                        |\n"
	"|                                                                     |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S3x  ::          :: Pitchmod ::               :: Super SNESMod NoFX |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S34 - Triangle                                                      |\n"
	"| S35 - Ramp Up                                                       |\n"
	"| S36 - Square 2                                                      |\n"
	"|                                                                     |\n"
	"|::::::::::::::::::::. ......................... .::::::::::::::::::::|\n"
	"|  ECHO WRITE FLAG  ::                           ::  ECHO WRITE FLAG  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S3x  ::          ::          ::               :: Super SNESMod NoFX |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S37 - Disable echo writes                                           |\n"
	"| S38 - Enable echo writes                                            |\n"
	"|                                                                     |\n"
	"|::::::::::::::. .................................... .:::::::::::::::|\n"
	"|  SET FILTER ::                                      ::  SET FILTER  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S3x ::          ::          ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
        "| S39 - Reset all coefficients, master and echo volume, echo feedback |\n"
        "|       and echo delay                                                |\n"
	"| S3A - Set default filter                                            |\n"
	"| S3B - Set bandpass filter                                           |\n"
	"| S3C - Set highpass filter                                           |\n"
	"| S3D - Set lowpass filter                                            |\n"
	"| S3E - Set ? filter (ren & stimpy)                                   |\n"
	"| S3F - Set ? filter (star ocean)                                     |\n"
	"|                                                                     |\n"
	"| * If S96 or S97 has been set then S3[A-F] will sweep to these       |\n"
	"|   preset filter values instead of immediately setting them          |\n"
	"|                                                                     |\n"
	"|:::::::::::::::::::::::::. ............... .:::::::::::::::::::::::::|\n"
	"|  SET TREMOLO WAVEFORM  ::                 ::  SET TREMOLO WAVEFORM  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S4x ::          ::          ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S40 - Sine [default]                                                |\n"
	"| S41 - Ramp down                                                     |\n"
	"| S42 - Square                                                        |\n"
	"|                                                                     |\n"
	"| * See note after panbrello commands.                                |\n"
	"|                                                                     |\n"
	"|::::::::::::::::::. ............................. .::::::::::::::::::|\n"
	"|  MISC COMMANDS  ::                               ::  MISC COMMANDS  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S4x ::          ::          ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S44 - EVOL max -> min                                               |\n"
	"| S45 - EVOL min -> max [default]                                     |\n"
	"| S46 - Enable swing tempo (Use S9D, ZF1-FF for different speeds. The |\n"
	"|       default is 1.)                                                |\n"
	"| S47 - Disable swing tempo [default]                                 |\n"
	"| S48 - Enable wavetable cycle. This replaces the first sample, which |\n"
	"|       should have a sample rate of 16744Hz with a length of 32,     |\n"
	"|       with wavetable samples. Up to 8 brr samples can be uploaded   |\n"
	"|       using spcChangeWaveTable.                                     |\n"
	"| S49 - Disable wavetable cycle [default] It is not possible to       |\n"
	"|       restore the original sample at this time.                     |\n"
	"| S4A - Noise frequency increase                                      |\n"
	"| S4B - Noise frequency decrease [default]                            |\n"
	"| S4C - Noise frequency repeat on                                     |\n"
	"| S4D - Noise frequency repeat off [default]                          |\n"
	"| S4E - Noise frequency ping pong on                                  |\n"
	"| S4F - Noise frequency ping pong off [default]                       |\n"
	"|                                                                     |\n"
	"|:::::::::::::::::::::::::::. ............ .::::::::::::::::::::::::::|\n"
	"|  SET PANBRELLO WAVEFORM  ::              :: SET PANBRELLO WAVEFORM  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S5x ::          ::          ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S50 - Sine [default]                                                |\n"
	"| S51 - Ramp down                                                     |\n"
	"| S52 - Square                                                        |\n"
	"|                                                                     |\n"
	"| * Vibrato, tremolo, and panbrello waveform may be set using S3x.    |\n"
	"|   The S4x and S5x commands are available if you need to hear what   |\n"
	"|   it will sound like in the tracker. When using Hxx, Rxx, and Yxx   |\n"
	"|   on the same channel they will use the same parameters if          |\n"
	"|   unspecified. If you use H42 for vibrato and later use R75 for     |\n"
	"|   tremolo, using H00 after the tremolo command is the same as using |\n"
        "|   H75.                                                              |\n"
	"|                                                                     |\n"
	"|::::::::::::::::::::::::::. ............. .::::::::::::::::::::::::::|\n"
	"|  NOISE FREQUENCY SWEEP  ::               ::  NOISE FREQUENCY SWEEP  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S5x ::          ::          ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S54-S5F - Start noise frequency sweep [-40h = starting frequency]   |\n"
	"|                                                                     |\n"
	"| * This is a shortcut for S9D ZMODE Z14-Z1F. Use ZDA-ZDF to alter    |\n"
	"|   the behavior of this command.                                     |\n"
	"|                                                                     |\n"
	"|::::::::::::::::::. ............................. .::::::::::::::::::|\n"
	"|  SOUND CONTROL  ::                               ::  SOUND CONTROL  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S9x ::  SNESMod :: Pitchmod ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S91 - Surround sound                                                |\n"
	"|                                                                     |\n"
	"|:::::::::::::::::. ................................ .::::::::::::::::|\n"
	"|  MUTE CHANNEL  ::                                  :: MUTE CHANNEL  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S9x ::          :: Pitchmod ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S92 - Mute channel for pitch modulation                             |\n"
	"| S93 - Unmute channel                                                |\n"
	"|                                                                     |\n"
	"| * It is not necessary to mute the channel providing the pitch       |\n"
	"|   factor.                                                           |\n"
	"|                                                                     |\n"
	"|::::::::::::::. ..................................... .::::::::::::::|\n"
	"|  SET ZMODE  ::                                       ::  SET ZMODE  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| S9x ::          ::          ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| S96 - Set ZMODE to channel filter sweep and reset EDL, EFB, EFIR,   |\n"
	"|       EVOL.                                                         |\n"
	"| S97 - Set ZMODE to channel filter sweep. Use Zxx to sweep to value  |\n"
	"|       xx on the current channel, or use S3[A-F] to sweep all        |\n"
	"|       all channels to pre-set filter values.                        |\n"
	"| S98 - Set ZMODE to modify the coefficients for the 8-tap FIR filter |\n"
	"| S99 - Set ZMODE to modify the master volume                         |\n"
	"| S9A - Set ZMODE to modify echo volume                               |\n"
	"| S9B - Set ZMODE to modify echo feedback                             |\n"
	"| S9C - Set ZMODE to modify echo delay and for special commands       |\n"
	"| S9D - Set ZMODE to modify echo volume sweep and noise sweep         |\n"
	"| S9E - Set ZMODE to modify echo sweep minimum and maximum values     |\n"
	"| S9F - Set ZMODE to enable filter sweep and change filter delay      |\n"
	"|                                                                     |\n"
        "|:::::::::::::::::::::::::::::. ....... .:::::::::::::::::::::::::::::|\n"
        "|  SET SUSTAIN RATE & LEVEL  ::         ::  SET SUSTAIN RATE & LEVEL  |\n"
        "|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
        "| Zxx ::  SNESMod :: Pitchmod ::               ::                     |\n"
        "|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
	"| Z00-FF - Set sustain rate and level for the current channel         |\n"
	"|          (%%rrrlllll)                                                |\n"
	"|                                                                     |\n"
	"|::::::::::::::::::. ............................. .::::::::::::::::::|\n"
	"|  SET PARAMETER  ::                               ::  SET PARAMETER  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"| Zxx ::          ::          ::               :: Super SNESMod NoFX  |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                                                                     |\n"
        "| [S96|S97]                                                           |\n"
	"|       Z80    - disable channel filter sweep for current channel     |\n"
	"|       Zxx    - sweep to this value* on the current channel          |\n"
	"|                                                                     |\n"
	"| [S98] Z80    - Reset coefficients to default                        |\n"
	"|       Zxx    - Set coefficient value* on the current channel        |\n"
	"|                                                                     |\n"
	"| [S99] Z80    - Reset master volume to default set in source code    |\n"
	"|       Zxx    - Set master volume                                    |\n"
	"|                Values >80h will slide master volume to echo volume  |\n"
	"|                level and echo volume to master volume level.        |\n"
	"|                                                                     |\n"
	"| [S9A] Z80    - Reset echo volume                                    |\n"
	"|       Zxx    - Set echo volume*                                     |\n"
	"|                                                                     |\n"
	"| [S9B] Z80    - Reset echo feedback                                  |\n"
	"|       Zxx    - Set echo feedback*                                   |\n"
	"|                                                                     |\n"
	"| [S9C] Z00-0F - Set echo delay                                       |\n"
	"|       Z10    - Reset all coefficients, master and echo volume, echo |\n"
	"|                feedback and echo delay                              |\n"
	"|       Z11-4F - Set delay between wavetable cycle update [-10h,x*4]  |\n"
	"|       Z50-57 - Set minimum wavetable [-50h]                         |\n"
	"|       Z58-5F - Set maximum wavetable [-58h]                         |\n"
	"|                                                                     |\n"
	"| [S9D] Z00-1F - Start noise frequency sweep                          |\n"
	"|       Z20-3F - Set minimum noise frequency value [-20h]             |\n"
	"|       Z40-5F - Set maximum noise frequency value [-40h]             |\n"
	"|       Z60    - Disable noise frequency sweep [default]              |\n"
	"|       Z61-D9 - Set noise frequency sweep speed                      |\n"
	"|       ZDA    - Noise frequency increase                             |\n"
	"|       ZDB    - Noise frequency decrease [default]                   |\n"
        "|       ZDC    - Noise frequency repeat on                            |\n"
	"|       ZDD    - Noise frequency repeat off [default]                 |\n"
	"|       ZDE    - Noise frequency ping pong on                         |\n"
	"|       ZDF    - Noise frequency ping pong off [default]              |\n"
	"|       ZE0    - Disable echo volume sweep                            |\n"
	"|       ZE1-EF - Enable echo volume sweep with speed x                |\n"
	"|       ZF0    - Disable swing tempo                                  |\n"
	"|       ZF1-FF - Enable swing tempo; mod_speed+x, mod_speed [-F0h]    |\n"
	"|                                                                     |\n"
	"| [S9E] Z00-7F - set minimum echo volume for filter sweep             |\n"
	"|       Z80-FF - set maximum echo volume for filter sweep             |\n"
	"|                                                                     |\n"
	"| [S9F] Z00    - Disable filter sweep                                 |\n"
	"|       Z01-FF - Delay before changing filter coefficients            |\n"
	"|                [default 80h]                                        |\n"
	"|                                                                     |\n"
	"| * Values >80h are negative numbers.                                 |\n"
	".                                                                     .\n"
	":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n"
	":    WARNING  WARNING  WARNING  WARNING  WARNING  WARNING  WARNING    :\n"
	":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n"
	".                                                                     .\n"
	"| * Be careful with the echo coefficient values! It's possible to     |\n"
	"|   cause harm to your speakers or your ears, especially if you've    |\n"
	"|   got headphones on.                                                |\n"
	"|                                                                     |\n"
	"|   From the Fullsnes - Nocash SNES Specs:                            |\n"
	"|                                                                     |\n"
	"|     To avoid addition overflows: The sum of POSITIVE values in the  |\n"
	"|     first seven registers (FIR0..FIR6) should not exceed +7Fh, and  |\n"
	"|     the sum of NEGATIVE values should not exceed -7Fh. The sum of   |\n"
	"|     all eight registers (FIR0..FIR7) should be usually around +80h  |\n"
	"|     (for leaving the overall output volume unchanged by the FIR     |\n"
	"|     unit; instead, echo volumes are usually adjusted via EFB/EVOL   |\n"
	"|     registers).                                                     |\n"
	"|                                                                     |\n"
	"| * Pitch modulation and noise generation are not completely safe for |\n"
	"|   video games because there aren't any checks for the sound effects |\n"
	"|   on the last two channels (it's especially bad if noise were to be |\n"
	"|   on those two channels... although pitch modulation can allow for  |\n"
	"|   some unusual effects to the music through the SFX if you want     |\n"
	"|   really unusual magic.).                                           |\n"
	"|                                                                     |\n"
	"| * Special commands such as Sxx and Zxx may overlap with unofficial  |\n"
	"|   add-on effects that have been applied since the original Impulse  |\n"
	"|   Tracker, however, SNESMod doesn't support those effects in the    |\n"
	"|   first place. They might affect playback when you're originally    |\n"
	"|   making the song in an unintended fashion, just to note.           |\n"
	".                                                                     .\n"
	":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n"
	":                        .: SAMPLE QUALITY .:                         :\n"
	":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n"
	".                                                                     .\n"
	"| 16-bit quality is recommended for the SPC samples, since they have  |\n"
	"| more data for compressing.                                          |\n"
	"|                                                                     |\n"
	"| If the loop width of an SPC sample is not a multiple of 16 then the |\n"
	"| sample will be unrolled OR resampled with linear interpolation for  |\n"
	"| alignment. (it will be resampled if unrolling uses too much memory) |\n"
	"|                                                                     |\n"
	"| Do not downsample your SPC samples too much or else they will sound |\n"
	"| like butt.                                                          |\n"
	"|                                                                     |\n"
	"| Sample offset is supported for the SPC samples, but there is a      |\n"
	"| small chance of creating unwanted NOISE because of the compression. |\n"
	"|                                                                     |\n"
	"| ALSO NOTE BIDI SAMPLES WILL BE UNROLLED AND USE UP LOTS OF SPACE.   |\n"
	"|                                                                     |\n"
	"| *ALSO* If you are making songs for a game remember that channel 8   |\n"
	"| will be OVERWRITTEN with sound effects. Don't put important stuff   |\n"
	"| there. This applies to SNESMod, Pitchmod, and Super SNESMod.        |\n"
	".                                                                     .\n"
	":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n"
	":                 .: SPECIAL SONG MESSAGE COMMANDS .:                 :\n"
	":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n"
	".                                                                     .\n"
	"| To control the default echo parameters for a module you must        |\n"
	"| specify some things in the song message.                            |\n"
	"|                                                                     |\n"
	"| To trigger this you must put an '[[SNESMOD]]' tag in your song      |\n"
	"| message followed by special commands!                               |\n"
	"|                                                                     |\n"
	"| See the example IT module, it has song message commands!            |\n"
	"|                                                                     |\n"
	"| Command List:                                                       |\n"
	"|                                                                     |\n"
	"| EDL <delay value>                                                   |\n"
	"|                                                                     |\n"
	"|   This sets the echo delay value. Range is 0-15                     |\n"
	"|   Delay time will be d*16 milliseconds.                             |\n"
	"|   NOTE: each 16ms of delay will use 2K of SPC memory. Your song's   |\n"
	"|   size limit will be more restricted with larger amounts of delay   |\n"
	"|   used.                                                             |\n"
	"|                                                                     |\n"
	"|   Issuing this command will enable echo (master) for the song       |\n"
	"|                                                                     |\n"
	"|   Example:                                                          |\n"
	"|                                                                     |\n"
	"|     'EDL 5'                                                         |\n"
	"|                                                                     |\n"
	"|   The echo delay time will be 5*16 (80) milliseconds. 10 Kilobytes  |\n"
	"|   will be taken away from the memory space, so it will have some-   |\n"
	"|   thing like 48 KB left.                                            |\n"
	"|                                                                     |\n"
	"| EFB <feedback level>                                                |\n"
	"|                                                                     |\n"
	"|   Set echo feedback level. Range is -128..127 (-100%%..100%%)         |\n"
	"|   Default value (if no command present) is 0.                       |\n"
	"|                                                                     |\n"
	"|   Example:                                                          |\n"
	"|                                                                     |\n"
	"|     'EFB 127'                                                       |\n"
	"|                                                                     |\n"
	"|   The echo feedback level will be set to 127, or 100%%.              |\n"
	"|   This value will probably destroy the sound because the feedback   |\n"
	"|   will cover the output.                                            |\n"
	"|                                                                     |\n"
	"| EVOL <volume> [volume right]                                        |\n"
	"|                                                                     |\n"
	"|   Set echo volume level. Range is -128..127.                        |\n"
	"|   One or two values may be given. If only one is specified then it  |\n"
	"|   will be used for both left and right outputs. If two values are   |\n"
	"|   given then one will be used for each output (left, right)         |\n"
	"|                                                                     |\n"
	"|   Examples:                                                         |\n"
	"|                                                                     |\n"
	"|     'EVOL 40'                                                       |\n"
	"|                                                                     |\n"
	"|   Both left and right echo outputs will have a volume of 40,        |\n"
	"|   or 31%%.                                                           |\n"
	"|                                                                     |\n"
	"|     'EVOL 31 -31'                                                   |\n"
	"|                                                                     |\n"
	"|   Left output will be 25%%, right output will be -25%%                |\n"
	"|                                                                     |\n"
	"|   Negative values will indeed inverse the phase of the applied      |\n"
	"|   waveform.                                                         |\n"
	"|                                                                     |\n"
	"| EFIR <c0> [c1] [c2] [c3] [c4] [c5] [c6] [c7]                        |\n"
	"|                                                                     |\n"
	"|   Specifies the coefficients for the 8-tap FIR filter applied to    |\n"
	"|   the echo output.                                                  |\n"
	"|                                                                     |\n"
	"|   Default values are 127, 0, 0, 0, 0, 0, 0, 0                       |\n"
	"|                                                                     |\n"
	"|   If less than 8 values are specified then the default values will  |\n"
	"|   be used for the rest of the entries.                              |\n"
	"|                                                                     |\n"
	"|   Example:                                                          |\n"
	"|                                                                     |\n"
	"|     'EFIR 64 -32 16'                                                |\n"
	"|                                                                     |\n"
	"|   Set the first three coefficients to these values and the rest     |\n"
	"|   will be zero.                                                     |\n"
	"|                                                                     |\n"
	"| EON <channels>                                                      |\n"
	"|                                                                     |\n"
	"|   Enable echo for the channels listed.                              |\n"
	"|                                                                     |\n"
	"|   Example:                                                          |\n"
	"|                                                                     |\n"
	"|     'EON 1 3 4 5'                                                   |\n"
	"|                                                                     |\n"
	"|   Enable echo for channels 1 (first), 3, 4, and 5.                  |\n"
	"|                                                                     |\n"
	"| Here is an example song message with commands in it:                |\n"
	"|---------------------------------------------------------------------|\n"
	"| Here is my song, blah blah blah blah                                |\n"
	"| By Ms.X                                                             |\n"
	"|                                                                     |\n"
	"| [[SNESMOD]]                                                         |\n"
	"| edl 6                                                               |\n"
	"| efb 127                                                             |\n"
	"| evol 31 -31                                                         |\n"
	"| efir 127 0 0 0 0 0 0 0                                              |\n"
	"| eon 1 2 3                                                           |\n"
	".                                                                     .\n"
	":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n"
	":                       .: SPACE SAVING TIPS .:                       :\n"
	":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n"
	".                                                                     .\n"
	"| * Remove commands that are not used. If you have commands and       |\n"
	"|   notes after the break pattern command you are wasting bytes.      |\n"
	"|                                                                     |\n"
	"| * Remove commands that are duplicated. It's not necessary to set    |\n"
	"|   the tempo on every pattern if you are not changing the value.     |\n"
	"|                                                                     |\n"
	"| * Volume envelopes can save a lot of space over using the volume    |\n"
	"|   commands.                                                         |\n"
	"|                                                                     |\n"
	"| * Don't bother with the pattern break command. Just set the         |\n"
	"|   pattern length.                                                   |\n"
	"|                                                                     |\n"
	"| * If there are two patterns where lines 00 - 1f are the same and    |\n"
	"|   lines 20-3f are different, cut the patterns in half.              |\n"
	"|                                                                     |\n"
	"|   For example, if you have two patterns 00 and 01, copy 00 to 02.   |\n"
	"|   Set the pattern length to 32. On patterns 00 and 01 move lines    |\n"
	"|   20-3f up to 00-1f and again set the pattern length to 32. Now     |\n"
	"|   the order is 02,00,02,01 instead of 00,01.                        |\n"
	"|                                                                     |\n"
	"| * Is the whole sample being used? If not, consider cutting it down. |\n"
	"|                                                                     |\n"
	"|:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::|\n"
	"|                            (PLEASE ENJOY)                           |\n"
	"`---------------------------------------------------------------------'\n"
	"  -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-\n"

};

#endif // HELP_H
