.ifndef __GRAPHICS_INC__
__GRAPHICS_INC__ = 1

.import gfx_16x16_fontTiles
.import gfx_16x16_fontPal

.import gfx_censor_ring_logoTiles
.import gfx_censor_ring_logoMap

.import gfx_censor_ring_bg2Tiles
.import gfx_censor_ring_bg2Map
.import gfx_censor_ring_bg2Pal

.import gfx_censor_ring_bg3Tiles
.import gfx_censor_ring_bg3Map
.import gfx_censor_ring_bg3Pal

.import gfx_censor_8x8_c64Tiles

.import gfx_censor_ring_sprTiles
.import gfx_censor_ring_sprPal

.endif
