.ifndef __GRAPHICS_INC__
__GRAPHICS_INC__ = 1

.import gfx_ballsTiles
.import gfx_ballsPal
.import gfx_ballsMap

.import gfx_bg3Tiles
.import gfx_bg3Pal

.import gfx_creditsTiles
.import gfx_creditsPal
.import gfx_creditsMap
.import gfx_credits_redPal

.import gfx_logo_swatTiles	; src in logo dir
.import gfx_logo_swatPal	; ''
.import gfx_logo_atxPal

.import gfx_scroll_goldPal
.import gfx_scroll_goldTiles

.endif
