.ifndef __GRAPHICS_INC__
__GRAPHICS_INC__ = 1

.import gfx_aeraTiles
.import gfx_aeraPal
.import gfx_aera_pal2Pal

.import gfx_alundra1Tiles
.import gfx_alundra1Pal
.import gfx_alundra1Map

.import gfx_alundra2Tiles
.import gfx_alundra2Pal
.import gfx_alundra2Map

.import gfx_alundra3Tiles
.import gfx_alundra3Pal
.import gfx_alundra3Map

.import gfx_titleTiles
.import gfx_titlePal
.import gfx_titleMap

.endif
