.ifndef __C64_PAL_INC__
__C64_PAL_INC__ = 1
;-------------------------------------------------------------------------;
BLACK		= 0000h
WHITE		= 7fffh
RED		= 1911h
CYAN		= 62efh
PURPLE		= 5511h
GREEN		= 228bh
BLUE		= 50c7h
YELLOW		= 375bh
ORANGE		= 1573h
BROWN		= 010ch
LT_RED		= 39f7h
GREY1		= 294ah
GREY2		= 4210h
LT_GREEN	= 47b5h
LT_BLUE		= 6dceh
GREY3		= 56b5h
;-------------------------------------------------------------------------;
GRAY1 = GREY1
GRAY2 = GREY2
GRAY3 = GREY3
DK_GRAY = GREY1
GRAY = GREY2
LT_GRAY = GREY3
DK_GREY = GREY1
GREY = GREY2
LT_GREY = GREY3
DEFAULT_BG_COLOR = BLUE
DEFAULT_BORDER_COLOR = LT_BLUE
;-------------------------------------------------------------------------;
.endif
