.ifndef __EGA_PAL_INC__
__EGA_PAL_INC__ = 1
;-------------------------------------------------------------------------;
BLACK		= 0000h
BLUE		= 5000h
GREEN		= 0280h
CYAN		= 5280h
RED		= 0014h
MAGENTA		= 5014h
BROWN		= 0154h
GREY1		= 5294h
GREY2		= 294ah
LT_BLUE		= 7d4ah
LT_GREEN	= 2beah
LT_CYAN		= 7feah
LT_RED		= 295fh
LT_MAGENTA	= 7d5fh
YELLOW		= 2bffh
WHITE		= 7fffh
;-------------------------------------------------------------------------;
GRAY1 = GREY1
GRAY2 = GREY2
GREY = GREY1
GRAY = GREY1
DK_GRAY = GREY1
LT_GRAY = GREY2
DK_GREY = GREY1
LT_GREY = GREY2
;-------------------------------------------------------------------------;
.endif
